AWSTemplateFormatVersion: '2010-09-09'
Description: Creates Generate PDF lambda function and registers a path in the API gateway
Parameters:
  RestApiId:
    Type: String
    AllowedPattern: '[A-Za-z0-9-]*'
Resources:
  GeneratePdfLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: GeneratePdfHandler.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.11
      Timeout: 120
      Code:
        S3Bucket: nutrition-labels-lambda
        S3Key: generate-pdf-lambda-function.zip
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: '*'
  NutritionLabelApiGeneratePdfIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref RestApiId
      Description: Integration for the PDF generation Lambda function
      IntegrationMethod: POST
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GeneratePdfLambdaFunction.Arn}/invocations
      PayloadFormatVersion: '2.0'
      TimeoutInMillis: 30000 # Adjust as needed
  NutritionLabelApiGeneratePdfRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref RestApiId # Ensure this references your HTTP API resource's ID
      RouteKey: POST /api/generate-pdf
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref NutritionLabelApiGeneratePdfIntegration
  LambdaApiGatewayInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GeneratePdfLambdaFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApiId}/*/*/*
