version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - cd webapp
      - npm install --prefer-offline
  pre_build:
    commands:
      - echo "Running tests (write some tests dummy)..."
artifacts:
  files:
    - webapp/dist/**/*
  base-directory: webapp/dist
cache:
  paths:
    - 'webapp/node_modules/**/*'
