version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - echo "Installing dependencies..."
      - npm install --prefer-offline
  pre_build:
    commands:
      - echo "Running tests (write some tests dummy)..."
  build:
    commands:
      - echo "Packaging application..."
      - zip -r generate-pdf-lambda-function.zip ./build
artifacts:
  files:
    - dist/**/*
  base-directory: dist
cache:
  paths:
    - 'node_modules/**/*'
